## Pre-determine the amount of memory you'll require
options(java.parameters = '-Xmx16G')

library(biscale)
library(classInt)
library(cowplot)
library(dplyr)
library(ggplot2)
# library(geojsonR)
library(here)
library(Hmisc)
library(hrbrthemes)
# library(link2GI)
# library(matrixStats)
library(moments)
# library(pacman)
library(purrr)
library(R2WinBUGS)
library(RColorBrewer)
library(reshape2)
# library(rgdal)
# library(rgrass7)
library(sf)
library(sp)
library(spatialreg)
library(spdep)
library(SpatialAcc)
library(tmap)
library(tidycensus)
library(tidyverse)
# library(wellknown)
library(stringr)
library(ggpubr)
library(r5r)
library(osmdata)
library(gtfstools)
library(osmextract)
library(readxl)
library(xlsx)
library(INLA)
library(nimble)
library(ggmcmc)
library(nlist)

source("PrEP_alcohol_function.R")
